---
application:
  name: "bdhsolver"
  project: "BDH Solver"
  organization: "QoveryCommunity"
  storage:
  - name: "dsk"
    size: "500"
    type: "slow_hdd"
    mount_point: "/mnt/dsk"
routers:
- name: "main-bdhsolver"
  routes:
  - application_name: "bdhsolver"
    paths:
    - "/*"
